dist: xenial

language: python

addons:
  apt:
    packages:
    - graphviz
    - libopenblas-dev
    - libqd-dev

os:
  - linux

python:
  - "3.6"
  - "3.7"

env:
  global:
    - USE_SYSTEM_QD=""

matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - USE_SYSTEM_QD=1

  allow_failures:
    - os: linux
      python: 3.6
      env:
        - USE_SYSTEM_QD=1

install:
  # default python provides an incompatible version of numpy (1.15.x) for python 3.7
  - pip install --upgrade pip setuptools numpy scipy
  - pip install -e ".[test]"

script:
  - pytest
